#HOSTADDRESS="10.42.16.17"
#NOTIFICATIONTYPE="PROBLEM"
#NOTIFICATIONTYPE="RECOVERY"
#HOSTNAME="TEST"
#HOSTSTATE="DOWN"
#LONGDATETIME="Fri Jan 15 14:01:54 MST 2016"

HOSTADDRESS=$1
NOTIFICATIONTYPE=$2
HOSTNAME=$3
HOSTSTATE=$4
LONGDATETIME=$5

DELETE="sqlite3 /Users/Aesir/Documents/watchdog/tcp_watchdog_server/alarmdb.db \"DELETE FROM ALARMS WHERE ID_NAME = '$HOSTADDRESS'\""

HOSTSTRING="** $NOTIFICATIONTYPE Host Alert: $HOSTNAME is $HOSTSTATE **"

ADD="sqlite3 /Users/Aesir/Documents/watchdog/tcp_watchdog_server/alarmdb.db \"INSERT OR REPLACE INTO ALARMS (ID_NAME,ALARM,TIMESTAMP) VALUES ('$HOSTADDRESS','$HOSTSTRING','$LONGDATETIME')\""

if [ $NOTIFICATIONTYPE = "PROBLEM" ]; then echo $ADD; else echo $DELETE; fi

if [ $NOTIFICATIONTYPE = "PROBLEM" ]; then eval $ADD; else eval $DELETE; fi
