#!/usr/bin/python

import sqlite3 as lite
import sys

con = lite.connect('demosdb.db')

with con:
    
    cur = con.cursor()    
    
    cur.execute("DROP TABLE IF EXISTS DEVICES")
    cur.execute("CREATE TABLE DEVICES(ID_NAME  TEXT PRIMARY KEY, LOCATION  TEXT, TIMESTAMP TEXT, UPTIME TEXT, UPTIME_SEC INT, STATUS TEXT, DEVICE_TYPE TEXT, LAST_RESET_TIMESTAMP TEXT, LAST_UPTIME_SEC INT, MAX_ID_NAME TEXT, ZONE TEXT, SPACE TEXT, DEVICE_NAME TEXT, DESCRIPTION TEXT)")
    cur.execute("DROP TABLE IF EXISTS LOCATIONS")
    cur.execute("CREATE TABLE LOCATIONS (ID_NAME TEXT PRIMARY KEY, LOCATION TEXT)")
    cur.execute("DROP TABLE IF EXISTS SYSTEM_INFO")
    cur.execute("CREATE TABLE SYSTEM_INFO (ID_NAME TEXT PRIMARY KEY, NUM_DEVICES INT, NUM_OKAY_DEVICES INT, PERCENT_OKAY INT)")



